[{"user_id":"1","encoded":"X","author":"Seung-soon Park","email":"N\/A","type":"static","website":"N\/A","location":"1 Gap-cheon, Yuseong-Gu","latitude":"36.361243","longitude":"127.357535","datetime":1473841900,"date":"December 1, 2014","date_link":"12.01.14","time":"12:34 PM","duration":"2:01","equipment":"ZOOM H1 Handy Recorder","binaural":"X","description":"A close-up recording of a medium-size stream.","cc":"X","soundfile":"ZOOM0006.mp3","download":"0001_sw_1st_ave_and_sw_ankeny_st_14-07-13.flac","complete":"X","sound_ext":".wav","image_lg":"/img/gapcheon.jpg","image_sm":"/img/gapcheon.jpg","sidelink":"1 Gap-cheon, Yuseong-Gu, 12.01.14","category":"Ripple", "region":"Daejon},


{"user_id":"2","encoded":"X","author":"Seung-soon Park","email":"N\/A","type":"static","website":"N\/A","location":"2 KAIST GSCT, Yuseong-Gu","latitude":"36.374373","longitude":"127.363956","datetime":1473842260,"date":"December 16, 2014","date_link":"12.16.14","time":"01:51 PM","duration":"1:00","equipment":"ZOOM H1 Handy Recorder","binaural":"X","description":"The sound of rippling water.","cc":"X","soundfile":"/audio/rippling-water-1.mp3","download":"/audio/rippling-water-1.wav","complete":"X","sound_ext":".wav","image_lg":"/img/dripping.jpg","image_sm":"/img/dripping.jpg","sidelink":"2 KAIST GSCT, Yuseong-Gu, 12.16.14"},


{"user_id":"3","encoded":"X","author":"Seung-soon Park ","email":"N\/A","type":"static","website":"N\/A","location":"3 Gap-cheon, Yuseong-Gu","latitude":"36.364159","longitude":"127.363984","datetime":1373844540,"date":"December 1, 2014","date_link":"12.01.14","time":"12:21 PM","duration":"1:00","equipment":"ZOOM H1 Handy Recorder","binaural":"X","description":"A close-up recording of a medium-size stream.","cc":"X","soundfile":"/audio/river-2.mp3","download":"/audio/river-2.wav","complete":"X","sound_ext":".wav","image_lg":"/img/gapcheon.jpg","image_sm":"/img/gapcheon.jpg","sidelink":"3 Gap-cheon, Yuseong-Gu, 12.01.14"},


{"user_id":"4","encoded":"X","author":"Seung-soon Park ","email":"N\/A","type":"static","website":"N\/A","location":"4 Gap-cheon, Yuseong-Gu","latitude":"36.365645","longitude":"127.368769","datetime":1374171780,"date":"December 1, 2014","date_link":"12.01.14","time":"12:54 PM","duration":"1:00","equipment":"ZOOM H1 Handy Recorder","binaural":"X","description":"A close-up recording of a medium-size stream.","cc":"X","soundfile":"/audio/river-6.mp3","download":"/audio/river-6.mp3","complete":"X","sound_ext":".mp3","image_lg":"/img/gapcheon.jpg","image_sm":"/img/gapcheon.jpg","sidelink":"4 Gap-cheon, Yuseong-Gu, 12.01.14"},


{"user_id":"5","encoded":"X","author":"Seung-soon Park","email":"N\/A","type":"static","website":"N\/A","location":"5 Tandong-cheon, Yuseong-Gu","latitude":"36.375858","longitude":"127.365260","datetime":1374297180,"date":"December 16, 2014","date_link":"12.16.14","time":"12:13 AM","duration":"1:00","equipment":"ZOOM H1 Handy Recorder","binaural":"0","description":"A tiny waterfall in the Tandong-stream.","cc":"X","soundfile":"/audio/stream-3.mp3","download":"/audio/stream-3.mp3","complete":"X","sound_ext":".mp3","image_lg":"/img/tandong.jpg","image_sm":"/img/tandong.jpg","sidelink":"5 Tandong-cheon, Yuseong-Gu, 12.16.14"},


{"user_id":"6","encoded":"X","author":"Seung-soon Park","email":"N\/A","type":"static","website":"N\/A","location":"6 KAIST GSCT, Yuseong-Gu","latitude":"36.373117","longitude":"127.363566","datetime":1378069440,"date":"December 17, 2014","date_link":"14.12.14","time":"05:04 PM","duration":"1:00","equipment":"ZOOM H1 Handy Recorder","binaural":"0","description":"Raining in the street, droplets hitting concrete at KAIST GSCT Building.","cc":"X","soundfile":"/audio/rain-04.mp3","download":"/audio/rain-04.mp3","complete":"X","sound_ext":".mp3","image_lg":"/img/rain.jpg","image_sm":"/img/rain.jpg","sidelink":"6 KAIST GSCT, Yuseong-Gu, 12.17.14"},


{"user_id":"7","encoded":"X","author":"Seung-soon Park","email":"N\/A","type":"static","website":"N\/A","location":"7 Tandong-cheon, Yuseong-Gu","latitude":"36.375443","longitude":"127.369267","datetime":1378067460,"date":"December 16, 2014","date_link":"12.16.14","time":"12:31 AM","duration":"1:00","equipment":"ZOOM H1 Handy Recorder","binaural":"0","description":"A tiny waterfall in the Tandong-stream.","cc":"X","soundfile":"/audio/stream-1.mp3","download":"/audio/stream-1.mp3","complete":"X","sound_ext":".mp3","image_lg":"/img/tandong.jpg","image_sm":"/img/tandong.jpg","sidelink":"7 Tandong-cheon, Yuseong-Gu, 12.16.14"},


{"user_id":"8","encoded":"X","author":"Seung-soon Park","email":"N\/A","type":"static","website":"N\/A","location":"8 Gap-cheon, Yuseong-Gu","latitude":"36.364558","longitude":"127.366435","datetime":1378070280,"date":"December 1, 2014","date_link":"12.01.14","time":"11:18 AM","duration":"1:00","equipment":"ZOOM H1 Handy Recorder","binaural":"0","description":"A close-up recording of a medium-size stream.","cc":"X","soundfile":"/audio/stream-2.mp3","download":"/audio/stream-2.mp3","complete":"X","sound_ext":".mp3","image_lg":"/img/gapcheon.jpg","image_sm":"/img/gapcheon.jpg","sidelink":"8 Gap-cheon, Yuseong-Gu, 12.01.14"},


{"user_id":"9","encoded":"X","author":"Seung-soon Park","email":"N\/A","type":"static","website":"N\/A","location":"9 Gap-cheon, Yuseong-Gu","latitude":"36.369841","longitude":"127.372611","datetime":1381015080,"date":"December 01, 2014","date_link":"12.01.14","time":"11:54 AM","duration":"1:00","equipment":"ZOOM H1 Handy Recorder","binaural":"0","description":"A close-up recording of a medium-size stream.","cc":"X","soundfile":"/audio/river-4.mp3","download":"/audio/river-4.wav","complete":"X","sound_ext":".wav","image_lg":"/img/gapcheon.jpg","image_sm":"/img/gapcheon.jpg","sidelink":"9 Gap-cheon, Yuseong-Gu, 12.01.14"}]